machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build --rm=false -t mega .

test:
  override:
    - docker run -d -p 9200:9200 mega; sleep 10
    - curl --retry 10 --retry-delay 5 -v http://localhost:9200
